import '/features/models/account_model.dart'; // Make sure this path matches your file structure
import '/features/models/transaction_model.dart';

final List<Account> dummyAccounts = [
  Account(
    id: 'acc_01',
    name: 'Main Wallet',
    balance: 154050,
    currency: Currency.usd,
    createdAt: DateTime(2022, 5, 10),
  ),
  Account(
    id: 'acc_02',
    name: 'Chase Savings',
    balance: 312221,
    currency: Currency.tl,
    createdAt: DateTime(2022, 6, 15),
  ),
  Account(
    id: 'acc_03',
    name: 'Revolut (Euro)',
    balance: 45075,
    currency: Currency.eur,
    createdAt: DateTime(2023, 1, 20),
  ),
  Account(
    id: 'acc_04',
    name: 'Travel Fund',
    balance: 2500000,
    currency: Currency.aud,
    createdAt: DateTime(2023, 3, 5),
  ),
  Account(
    id: 'acc_05',
    name: 'Joint Account',
    balance: 320000,
    currency: Currency.tl,
    createdAt: DateTime(2022, 11, 30),
  ),
  Account(
    id: 'acc_06',
    name: 'Cash on Hand',
    balance: 12000,
    currency: Currency.usd,
    createdAt: DateTime(2023, 4, 12),
  ),
  Account(
    id: 'acc_06',
    name: 'Cash on Hand',
    balance: 12000,
    currency: Currency.usd,
    createdAt: DateTime(2023, 4, 12),
  ),
  Account(
    id: 'acc_06',
    name: 'Cash on Hand',
    balance: 12000,
    currency: Currency.usd,
    createdAt: DateTime(2023, 4, 12),
  ),
  Account(
    id: 'acc_06',
    name: 'Cash on Hand',
    balance: 12000,
    currency: Currency.usd,
    createdAt: DateTime(2023, 4, 12),
  ),
  Account(
    id: 'acc_06',
    name: 'Cash on Hand',
    balance: 12000,
    currency: Currency.usd,
    createdAt: DateTime(2023, 4, 12),
  ),
  Account(
    id: 'acc_06',
    name: 'Cash on Hand',
    balance: 12000,
    currency: Currency.usd,
    createdAt: DateTime(2023, 4, 12),
  ),
  Account(
    id: 'acc_06',
    name: 'Cash on Hand',
    balance: 12000,
    currency: Currency.usd,
    createdAt: DateTime(2023, 4, 12),
  ),
  Account(
    id: 'acc_06',
    name: 'Cash on Hand',
    balance: 12000,
    currency: Currency.usd,
    createdAt: DateTime(2023, 4, 12),
  ),
];
